require: rubocop-sketchup

inherit_from:
  - https://raw.githubusercontent.com/SketchUp/rubocop-sketchup/master/sketchup-style.yml
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - src/*/vendor/**/*
    - yard-tools/**/*
  SketchUp:
    SourcePath: modules
    TargetSketchUpVersion: 2014
    Exclude:
      - skippy/**/*
      - tests/**/*
      - tools/**/*
  TargetRubyVersion: 2.2 # Should have been 2.0 but RuboCop dropped support.


# Doesn't apply to this project because it's not an extension.
SketchupRequirements/FileStructure:
  Enabled: false

SketchupRequirements/SketchupExtension:
  Enabled: false


Naming/AccessorMethodName:
  Exclude:
    - modules/command.rb # This method reads clearer with set_

Naming/ClassAndModuleCamelCase:
  Exclude:
    - tests/**/*

Naming/FileName:
  Exclude:
    - tests/**/*

Naming/MethodName:
  Exclude:
    - tests/**/*


# These hides methods of the parent class.
Style/AccessModifierDeclarations:
  Exclude:
    - modules/line.rb
    - modules/plane.rb
